### ISSUE TITLE
install error..

### ISSUE THREAD

**Issue by BBlume** [onehungrymind/ng2-bootstrap-daterangepicker#1]
hey there! 
I cloned the repo just as in the description... but when I run npm install the following appears.
I have ssh keys added.. so that should not be the problem...

`Bens-MBP:ng2-bootstrap-daterangepicker ben$ npm install
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: Cloning into bare repository '/Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52'...
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: Permission denied (publickey).
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: 
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52: and the repository exists.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/ben/.npm/_git-remotes/_templates --mirror git@github.com:simpulton/ng2-daterangepicker.git /Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52
npm ERR! Cloning into bare repository '/Users/ben/.npm/_git-remotes/git-github-com-simpulton-ng2-daterangepicker-git-69b97b52'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ben/WebstormProjects/test/ng2-bootstrap-daterangepicker/npm-debug.log`

I also tried another repo and there it works fine...

**Comment by BBlume** [comment]
Are there any updates on this issue?

**Comment by simpulton** [comment]
I just downloaded and installed the repository without error via ssh and https.

**Comment by BBlume** [comment]
well this is pretty weird! 
I have added my ssh keys. 
I clone.. all ok
as soon as i want to install that error appears.....
to check if I'm not completely out of my mind I cloned 
git clone https://github.com/onehungrymind/fem-ng2-simple-app.git
and installed it...no errors all good.
I started my dusty windows computer .. added ssh keys cloned and tried to install... same error. 
fem-ng2... worked....

**Comment by bona1337** [comment]
@simpulton same issue here. not enough access rights.

**Comment by simpulton** [comment]
Ok we found the problem! One of the packages this app depends on was actually a private repo of mine, which was why it worked for me but not anyone else. I've made that repo public, please verify you can install now. Thanks!

**Comment by bona1337** [comment]
thanks! yes working now! 👍
